### ISSUE TITLE
Invalid prop `dataField` of type `array` supplied to `DateRange`, expected `string`.

### ISSUE THREAD

**Issue by soflass1293** [appbaseio/reactive-manual#87]
Hello
I wanted to filter data by date. I have two fields "startDate" and "endDate" so I opted to use the DateRange with the option of using two fields in dataField...
In the official documentation of the DateRange is written:
dataField String or Array
database field(s) to be connected to the component’s UI view.
https://opensource.appbase.io/reactive-manual/range-components/daterange.html
But when I use an array of two strings I get a warning Invalid prop `dataField` of type `array` supplied to `DateRange`, expected `string`.
`              <DateRange
                  ...
                  dataField={["MY_START_DATE", "MY_END_DATE"]}
                  ...
                 />
`

**Comment by metagrover** [comment]
This is because, we support only one field (hence string) in the `DateRange` component. If you wish to use two fields in this component, I'd suggest you to use a `customQuery`. [Check this codesandbox for example](https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/dev/packages/web/examples/DateRange?from-embed).

**Comment by metagrover** [comment]
Thanks for bringing this up. Track the progress here: https://github.com/appbaseio/reactivesearch/issues/421

**Comment by davidklebanoff** [comment]
This can be closed now... Unless you want to wait until release.
